# Scikit-learn Built-in DataSet

In [1]:
import pandas as pd
# 為了顯示的漂亮, 我刻意的把印出來的 row 只顯示 10 個和 column 只顯示十個
# 大家練習的時候可以去掉下面兩行
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
# 讀者可以自行把下面行的註解拿掉 印出 iris
# iris

In [4]:
# 先用 data 和他的 column 創出 df
df = pd.DataFrame(data= iris['data'], columns= iris['feature_names'])
df["target"] = iris["target"]
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [5]:
from sklearn.datasets import load_boston
boston = load_boston()
# 讀者可以自行把下面行的註解拿掉 印出 boston
# boston

In [6]:
df = pd.DataFrame(data = boston['data'], columns = boston['feature_names'])
df['target'] = boston['target']
df

,CRIM,ZN,INDUS,CHAS,NOX,...,TAX,PTRATIO,B,LSTAT,target
0,0.00632,18.0,2.31,0.0,0.538,...,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,...,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,...,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,...,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,...,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,...,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,...,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,...,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,...,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,...,273.0,21.0,396.90,7.88,11.9